name: release

on:
  push:
    tags:
      # First tag is fabric-1.19.3-v0.0.0
      - fabric-1.19.3-v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: build/libs/*.jar

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        draft: true
        makeLatest: true
        name: ${{ github.ref_name }}
        artifacts: build/libs/*.jar
        token: ${{ secrets.GITHUB_TOKEN }}
